# Generated by Django 4.0.1 on 2022-01-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Hungarian', 'Hungarian'), ('English', 'English')], max_length=16)),
                ('for_who', models.CharField(choices=[('Everybody', 'Everybody'), ('Only civils', 'Only civils'), ('Only GOVs', 'Only GOVs'), ('Nobody', 'Nobody')], max_length=16)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Work Experience', 'Work Experience'), ('IT skills', 'IT skills'), ('Spoken languages', 'Spoken languages'), ('Others', 'Others')], max_length=64)),
                ('date', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.CharField(max_length=128)),
                ('path_to_the_document', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Hungarian', 'Hungarian'), ('English', 'English')], max_length=16)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Skype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skype', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Hungarian', 'Hungarian'), ('English', 'English')], max_length=16)),
                ('for_who', models.CharField(choices=[('Everybody', 'Everybody'), ('Only civils', 'Only civils'), ('Only GOVs', 'Only GOVs'), ('Nobody', 'Nobody')], max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('birthday', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('google_maps_link_for_address', models.URLField()),
                ('path_to_my_small_photo', models.CharField(max_length=128)),
                ('path_to_my_large_photo', models.CharField(max_length=128)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_api.email')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_api.phonenumber')),
                ('skype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_api.skype')),
            ],
        ),
    ]
