# Generated by Django 4.0.1 on 2022-01-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datas',
            options={'verbose_name_plural': 'Datas'},
        ),
        migrations.AlterModelOptions(
            name='personalinfos',
            options={'verbose_name_plural': 'Personal Infos'},
        ),
    ]
