# Generated by Django 4.0.1 on 2022-01-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0003_alter_datas_options_alter_personalinfos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfos',
            name='my_photo_alt',
            field=models.CharField(default='my_photo', max_length=32),
        ),
    ]
