# Generated by Django 4.0.1 on 2022-01-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0004_personalinfos_my_photo_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(default='balazs-mark', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'GitHub Accounts',
            },
        ),
    ]
