# Generated by Django 4.0.1 on 2022-01-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0005_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfos',
            name='github',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cv_api.github'),
        ),
        migrations.AlterField(
            model_name='github',
            name='github',
            field=models.CharField(max_length=32),
        ),
    ]
