# Generated by Django 4.0.1 on 2022-01-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0006_personalinfos_github_alter_github_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfos',
            name='github',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_api.github'),
        ),
    ]
