# Generated by Django 4.0.1 on 2022-01-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Hungarian', 'Hungarian'), ('English', 'English')], max_length=16)),
                ('for_who', models.CharField(choices=[('Everybody', 'Everybody'), ('Only civils', 'Only civils'), ('Only GOVs', 'Only GOVs'), ('Nobody', 'Nobody')], max_length=16)),
                ('button_id', models.CharField(max_length=128)),
                ('alt_for_icon', models.CharField(max_length=128)),
                ('path_of_icon', models.CharField(max_length=128)),
                ('text_on_button', models.CharField(max_length=128)),
                ('path_to_open_on_click', models.CharField(max_length=128)),
            ],
        ),
    ]
