export const CV_CONTENT_UPDATE_REQUEST = 'CV_CONTENT_UPDATE_REQUEST'
export const CV_CONTENT_UPDATE_SUCCESS = 'CV_CONTENT_UPDATE_SUCCESS'
export const CV_CONTENT_UPDATE_FAIL = 'CV_CONTENT_UPDATE_FAIL'
